load_data_args:
    neg_strategy: "random"

random_model_args:
    top_k: 10

semantic_model_args:
    top_k: 10
    nb_epochs: 0
    
syntactic_model_args:
    top_k: 10
    nb_epochs: 0
    
graph_model_args:
    max_epochs: 100
    graph_dim_embeddings: 512
    learning_rate: 0.001

hybrid_model_args:
    batch_size: 128
    num_workers: 0
    nb_epochs: 100
    num_classes: 2
    learning_rate: 0.001
    hidden_layer_dim: 384
    top_k: 10

hybrid_similarity_model_args:
    batch_size: 128
    num_workers: 0
    nb_epochs: 100
    num_classes: 2
    learning_rate: 0.001
    hidden_layer_dim: 384
    top_k: 10

hybrid_model_syn_sem_embed_gen_args:
    batch_size: 128
    num_workers: 1
    nb_epochs: 100
    num_classes: 2
    learning_rate: 0.001
    hidden_layer_dim: 384
    top_k: 10

hybrid_model_syn_sem_graph_embed_gen_args:
    batch_size: 128
    num_workers: 1
    nb_epochs: 100
    num_classes: 2
    learning_rate: 0.001
    hidden_layer_dim: 384
    top_k: 10